CREATE TABLE IF NOT EXISTS users (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(64) NOT NULL,
    email             VARCHAR(64) NOT NULL UNIQUE,
    password          VARCHAR(64) NOT NULL,
    about_me          VARCHAR(256),
    registration_type INTEGER NOT NULL
);